name: some trial on actions

on:
  push:
    branches:
      - tmp-action
    tags:
      - '*'

env:
  artifactName: ${{ github.event_name == 'tag' && join('artifact-', github.event_name) || 'artifact' }}

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: ls
        run: |
          ls > ls.out
          echo 'github.event_name: ${{ github.event_name }}'
          echo 'github.ref: ${{ github.ref }}'
          echo 'github.ref_name: ${{ github.ref_name }}'
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifactName }}
          path: '*'

